MODEL:
  PRETRAIN_CHOICE: 'imagenet' # If you are using pre-trained raw weights, such as those named ‘transformer_60.pth’, set this option to ‘clip’.
  # PRETRAIN_CHOICE: 'clip'
  PRETRAIN_PATH: 'weights/vit_base_p16_224-4e355ebd.pth'
  METRIC_LOSS_TYPE: 'triplet'
  IF_LABELSMOOTH: 'off'
  IF_WITH_CENTER: 'no'
  NAME: 'CMFGO'
  NO_MARGIN: True
  DEVICE_ID: ('2')
  TRANSFORMER_TYPE: 'vit_base_patch16_224_TransOSS'
  STRIDE_SIZE: [16, 16]
  MIE: True
  MIE_COE: 3.0
  SSE: True
  PAIR: False

INPUT:
  # SIZE_TRAIN: [256, 128]
  # SIZE_TEST: [256, 128]
  SIZE_TRAIN: [224, 224]
  SIZE_TEST: [224, 224]
  PROB: 0.5 # random horizontal flip
  RE_PROB: 0.5 # random erasing
  PADDING: 10
  PIXEL_MEAN: [0.485, 0.456, 0.406]
  PIXEL_STD: [0.229, 0.224, 0.225]

DATASETS:
  # NAMES: ('HOSS')
  # ROOT_DIR: ('dataset')
  # ROOT_DIR: ('dataset')
  NAMES: ('CMFGO')
  ROOT_DIR: ('../dataset')
  # ROOT_DIR: ('dataset')

DATALOADER:
  SAMPLER: 'softmax_triplet'
  NUM_INSTANCE: 16
  NUM_WORKERS: 8

SOLVER:
  OPTIMIZER_NAME: 'SGD'
  MAX_EPOCHS: 200
  BASE_LR: 0.0005
  # IMS_PER_BATCH: 32
  # IMS_PER_BATCH: 512
  IMS_PER_BATCH: 256
  WARMUP_METHOD: 'linear'
  LARGE_FC_LR: False
  CHECKPOINT_PERIOD: 10
  LOG_PERIOD: 80
  EVAL_PERIOD: 10
  WEIGHT_DECAY:  1e-4
  WEIGHT_DECAY_BIAS: 1e-4
  BIAS_LR_FACTOR: 2

TEST:
  EVAL: True
  IMS_PER_BATCH: 1024
  RE_RANKING: False
  WEIGHT: ''
  NECK_FEAT: 'before'
  FEAT_NORM: 'yes'

OUTPUT_DIR: './logs/CMFGO_O2S'
